version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-portfolio
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfolio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass123
    ports:
      - "8080:8080"
    networks:
      - backend-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://backend:8080
    ports:
      - "3000:3000"
    networks:
      - backend-net

volumes:
  pgdata:

networks:
  backend-net:
